steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/ultmt-app-dev/ultmt-services/ultmt-site', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/ultmt-app-dev/ultmt-services/ultmt-site']
options:
  logging: CLOUD_LOGGING_ONLY