name: Deploy

on:
  push:
    branches:
      - dev
      - e2e
      - main
  workflow_call:

jobs:
  get-environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}
    steps:
      - name: Some check on branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "env_name=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/e2e" ]; then
            echo "env_name=e2e" >> $GITHUB_OUTPUT
          else
            echo "env_name=dev" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: [test, get-environment]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.get-environment.outputs.env_name }}
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      
      - name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      
      - name: "Deploy Registry"
        run: |
          gcloud builds submit --config=cloudbuild.${{ needs.get-environment.outputs.env_name }}.yml .

      - name: "Deploy Cloud Run"
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'ultmt-site'
          image: ${{ vars.CONTAINER_REPOSITORY }}
          region: us-east4
          secrets: |
            API_URL=GATEWAY_URL:latest
            API_KEY=GATEWAY_API_KEY:latest

